### ISSUE TITLE
Feature Request: Material You

### ISSUE THREAD

**Issue by Jak2k** [zTomz/Textly#1]
Please use the latest Material You standards. Currently there is a lot space wasted and it doesn't integrate in the design of android.

**Comment by zTomz** [comment]
My app has an older design on purpose. Because I find this design more unique than the others. If you have a better design suggestion, please contact me at: tom.fe3dback@gmail.com.

**Comment by Jak2k** [comment]
You can also close this issue as "not planned". (Reopen and then close as not planned)

**Comment by zTomz** [comment]
Fixed with newest commit.
